export const navItems = [
  { label: "Problema", href: "#problema" },
  { label: "Valor", href: "#valor" },
  { label: "Resultados", href: "#resultados" },
  { label: "Fluxo", href: "#fluxo" },
  { label: "Metodologia", href: "#metodologia" },
  { label: "Catálogo", href: "#catalogo-entradas" },
  { label: "Estimativas", href: "#mapa" },
  { label: "Preço", href: "#preco" },
  { label: "FAQ", href: "#faq" },
];

export const integrationRows = [
  { label: "API REST bem documentada", level: "Baixa", levelClass: "tag-low", price: "+ R$ 4k a 12k" },
  { label: "Webhooks (Receber eventos)", level: "Baixa", levelClass: "tag-low", price: "+ R$ 3k a 10k" },
  { label: "Arquivo CSV (Import manual)", level: "Baixa/Média", levelClass: "tag-low", price: "+ R$ 3k a 12k" },
  { label: "GraphQL", level: "Média", levelClass: "tag-med", price: "+ R$ 8k a 18k" },
  { label: "API REST \"Ruim\"/Instável", level: "Média", levelClass: "tag-med", price: "+ R$ 10k a 25k" },
  { label: "Arquivo CSV via Pasta/SFTP", level: "Média", levelClass: "tag-med", price: "+ R$ 8k a 20k" },
  { label: "Procedure/Job no Banco", level: "Média", levelClass: "tag-med", price: "+ R$ 8k a 22k" },
  { label: "SOAP / XML (Legado)", level: "Média/Alta", levelClass: "tag-high", price: "+ R$ 12k a 30k" },
  { label: "Banco Direto (Read/Write)", level: "Alta (Risco)", levelClass: "tag-high", price: "+ R$ 12k a 35k" },
  { label: "RPA / UI (Clicar na tela)", level: "Alta", levelClass: "tag-high", price: "+ R$ 20k a 60k" },
  { label: "Integração Híbrida", level: "Muito Alta", levelClass: "tag-high", price: "+ R$ 25k a 80k" },
];

export const captureRows = [
  { label: "E-mail (IMAP/Graph)", level: "Baixa", levelClass: "tag-low", price: "+ R$ 3k-12k" },
  { label: "Portal / Formulário", level: "Baixa", levelClass: "tag-low", price: "+ R$ 4k-15k" },
  { label: "Pastas (Drive/SharePoint)", level: "Média", levelClass: "tag-med", price: "+ R$ 5k-18k" },
  { label: "SFTP / FTP", level: "Média", levelClass: "tag-med", price: "+ R$ 6k-18k" },
  { label: "WhatsApp Oficial", level: "Média", levelClass: "tag-med", price: "+ R$ 8k-25k" },
  { label: "API de Parceiro", level: "Média", levelClass: "tag-med", price: "+ R$ 6k-22k" },
];

export const documentModules = [
  {
    title: "Extração Template Fixo",
    description: "Regex e regras posicionais (ex. Boleto)",
    iconClass: "fa-file-contract",
    iconColor: "text-[#34D399]",
    tag: "Baixa",
    tagClass: "tag-sec",
    price: "+ R$ 3k a 10k",
  },
  {
    title: "Extração Variações Leves",
    description: "2 a 5 layouts similares conhecidos",
    iconClass: "fa-clone",
    iconColor: "text-[#60A5FA]",
    tag: "Média",
    tagClass: "tag-gov",
    price: "+ R$ 8k a 20k",
  },
  {
    title: "OCR (Scan/Foto)",
    description: "Documentos físicos digitalizados/fotos",
    iconClass: "fa-camera",
    iconColor: "text-[#F59E0B]",
    tag: "Média/Alta",
    tagClass: "tag-infra",
    price: "+ R$ 10k a 30k",
  },
  {
    title: "IA Generativa (LLM)",
    description: "Texto não-estruturado e layouts variáveis",
    iconClass: "fa-brain",
    iconColor: "text-[#A78BFA]",
    tag: "Alta",
    tagClass: "tag-infra",
    price: "+ R$ 12k a 35k",
  },
  {
    title: "Validação + Score",
    description: "Cálculo de confiança (Confidence Score)",
    iconClass: "fa-list-check",
    iconColor: "text-[#34D399]",
    tag: "Média",
    tagClass: "tag-gov",
    price: "+ R$ 6k a 18k",
  },
  {
    title: "Antifraude / Duplicidade",
    description: "Check contra base histórica",
    iconClass: "fa-user-shield",
    iconColor: "text-[#EF4444]",
    tag: "Média",
    tagClass: "tag-gov",
    price: "+ R$ 6k a 20k",
  },
  {
    title: "Human-in-the-loop",
    description: "Interface para revisão manual de exceções",
    iconClass: "fa-glasses",
    iconColor: "text-[#EC4899]",
    tag: "Alta",
    tagClass: "tag-infra",
    price: "+ R$ 15k a 45k",
  },
];

export const enterpriseModules = [
  {
    title: "Autenticação Corporativa",
    description: "SSO / OAuth / SAML",
    iconClass: "fa-key",
    iconColor: "text-[#60A5FA]",
    tag: "Segurança",
    tagClass: "tag-sec",
    price: "+ R$ 6k a 20k",
  },
  {
    title: "Auditoria e Trilha",
    description: "Logs completos (quem fez o quê)",
    iconClass: "fa-file-signature",
    iconColor: "text-[#34D399]",
    tag: "Compliance",
    tagClass: "tag-comp",
    price: "+ R$ 5k a 18k",
  },
  {
    title: "Aprovação em Etapas",
    description: "Workflow com alçadas de decisão",
    iconClass: "fa-sitemap",
    iconColor: "text-[#F59E0B]",
    tag: "Governança",
    tagClass: "tag-gov",
    price: "+ R$ 8k a 25k",
  },
  {
    title: "Monitoramento + Alertas",
    description: "Health check e notificação de erro",
    iconClass: "fa-bell",
    iconColor: "text-[#A78BFA]",
    tag: "Operação",
    tagClass: "tag-infra",
    price: "+ R$ 4k a 15k",
  },
  {
    title: "Multiempresa / Multitenant",
    description: "Gestão de múltiplos CNPJs/Filiais",
    iconClass: "fa-building",
    iconColor: "text-[#EC4899]",
    tag: "Escala",
    tagClass: "tag-gov",
    price: "+ R$ 10k a 35k",
  },
  {
    title: "Alta Disponibilidade / Fila",
    description: "Retry avançado e resiliência",
    iconClass: "fa-server",
    iconColor: "text-[#EF4444]",
    tag: "Infra",
    tagClass: "tag-infra",
    price: "+ R$ 10k a 40k",
  },
  {
    title: "LGPD e Privacidade",
    description: "Minimização, retenção e consentimento",
    iconClass: "fa-user-lock",
    iconColor: "text-[#60A5FA]",
    tag: "Jurídico",
    tagClass: "tag-comp",
    price: "+ R$ 6k a 25k",
  },
  {
    title: "Integração BI/Analytics",
    description: "Visibilidade de dados para gestão",
    iconClass: "fa-chart-pie",
    iconColor: "text-[#FCD34D]",
    tag: "Gestão",
    tagClass: "tag-gov",
    price: "+ R$ 5k a 20k",
  },
];
